---
# tasks file for wait-start
- name:
  wait_for_connection:

- name:  wait for host to finish reb00t
  wait_for:
    port: "{{ (ansible_port|default(ansible_ssh_port))|default(22) }}"
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
